name: update

on:
  workflow_dispatch:
  schedule:
    # Every Sunday at 00:00 UTC
    - cron: '0 0 * * 0'

permissions:
  contents: write
  pull-requests: write

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            filter-syscalls = false
            experimental-features = nix-command flakes
      - name: nix-update
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          nix run github:Mic92/nix-update -- --flake --use-update-script --write-commit-message commit.md piv-agent
      - name: commit message
        id: commit-message
        run: |
          if [ ! -f commit.md ]; then
            echo "No updates found." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi
          echo "message<<EOF" >> $GITHUB_OUTPUT
          cat commit.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          rm commit.md

      - uses: peter-evans/create-pull-request@v8
        if: ${{ steps.commit-message.outputs.message }}
        with:
          commit-message: ${{ steps.commit-message.outputs.message }}
          title: ${{ steps.commit-message.outputs.message }}
          body: |
            This PR was automatically generated by the nix update workflow.

            See workflow run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          branch: update-piv-agent
